blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation
    url: https://github.com/skarllot/Expressions#guide
    about: Read our documentation.
  - name: â­ Sponsor Raiqub Expressions
    url: https://www.buymeacoffee.com/skarllot
    about: Help the continued development.
  - name: ğŸ’¬ Ask on Github Discussions
    url: https://github.com/skarllot/Expressions/discussions
    about: The best place for asking general purpose questions.
